In [16]:
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt

In [17]:
tick = "AAPL"
ticker = yf.Ticker(tick)
data = ticker.history(period = "max")
print(data)

                                 Open        High         Low       Close  \
Date
1980-12-12 00:00:00-05:00    0.098122    0.098549    0.098122    0.098122
1980-12-15 00:00:00-05:00    0.093430    0.093430    0.093003    0.093003
1980-12-16 00:00:00-05:00    0.086604    0.086604    0.086177    0.086177
1980-12-17 00:00:00-05:00    0.088310    0.088737    0.088310    0.088310
1980-12-18 00:00:00-05:00    0.090870    0.091297    0.090870    0.090870
...                               ...         ...         ...         ...
2026-08-31 00:00:00-04:00  319.600006  321.239990  312.799988  316.850006
2026-09-01 00:00:00-04:00  316.980011  327.299988  314.730011  325.130005
2026-09-02 00:00:00-04:00  326.869995  328.399994  323.529999  324.959991
2026-09-03 00:00:00-04:00  324.869995  330.809998  324.109985  328.209991
2026-09-04 00:00:00-04:00  328.309998  328.929993  317.859985  319.970001

                              Volume  Dividends  Stock Splits
Date
1980-12-12 00:00:00-05:00  469033600        0.0           0.0
1980-12-15 00:00:00-05:00  175884800        0.0           0.0
1980-12-16 00:00:00-05:00  105728000        0.0           0.0
1980-12-17 00:00:00-05:00   86441600        0.0           0.0
1980-12-18 00:00:00-05:00   73449600        0.0           0.0
...                              ...        ...           ...
2026-08-31 00:00:00-04:00   41242700        0.0           0.0
2026-09-01 00:00:00-04:00   53167400        0.0           0.0
2026-09-02 00:00:00-04:00   33776400        0.0           0.0
2026-09-03 00:00:00-04:00   37225800        0.0           0.0
2026-09-04 00:00:00-04:00   39551800        0.0           0.0

[11525 rows x 7 columns]

In [18]:
df = pd.DataFrame(data)
df = df.reset_index()
df

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,1980-12-12 00:00:00-05:00,0.098122,0.098549,0.098122,0.098122,469033600,0.0,0.0
1,1980-12-15 00:00:00-05:00,0.093430,0.093430,0.093003,0.093003,175884800,0.0,0.0
2,1980-12-16 00:00:00-05:00,0.086604,0.086604,0.086177,0.086177,105728000,0.0,0.0
3,1980-12-17 00:00:00-05:00,0.088310,0.088737,0.088310,0.088310,86441600,0.0,0.0
4,1980-12-18 00:00:00-05:00,0.090870,0.091297,0.090870,0.090870,73449600,0.0,0.0
...,...,...,...,...,...,...,...,...
11520,2026-08-31 00:00:00-04:00,319.600006,321.239990,312.799988,316.850006,41242700,0.0,0.0
11521,2026-09-01 00:00:00-04:00,316.980011,327.299988,314.730011,325.130005,53167400,0.0,0.0
11522,2026-09-02 00:00:00-04:00,326.869995,328.399994,323.529999,324.959991,33776400,0.0,0.0
11523,2026-09-03 00:00:00-04:00,324.869995,330.809998,324.109985,328.209991,37225800,0.0,0.0
11524,2026-09-04 00:00:00-04:00,328.309998,328.929993,317.859985,319.970001,39551800,0.0,0.0

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11525 entries, 0 to 11524
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          11525 non-null  datetime64[s, America/New_York]
 1   Open          11525 non-null  float64
 2   High          11525 non-null  float64
 3   Low           11525 non-null  float64
 4   Close         11525 non-null  float64
 5   Volume        11525 non-null  int64
 6   Dividends     11525 non-null  float64
 7   Stock Splits  11525 non-null  float64
dtypes: datetime64[s, America/New_York](1), float64(6), int64(1)
memory usage: 720.4 KB

In [20]:
df.describe()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,11525.000000,11525.000000,11525.000000,11525.000000,1.152500e+04,11525.000000,11525.000000
mean,31.654362,32.001550,31.332176,31.681647,3.058985e+08,0.000920,0.001475
std,65.098495,65.816578,64.453487,65.168515,3.324280e+08,0.013561,0.081728
min,0.037969,0.037969,0.037542,0.037542,0.000000e+00,0.000000,0.000000
25%,0.249558,0.254294,0.243016,0.249558,1.035688e+08,0.000000,0.000000
50%,0.564544,0.576228,0.552393,0.565011,1.949948e+08,0.000000,0.000000
75%,22.745346,23.005598,22.641616,22.840561,3.856720e+08,0.000000,0.000000
max,339.736982,344.273097,337.059318,339.786926,7.421641e+09,0.270000,7.000000

In [22]:
df = df.drop(columns= "Dividends")
df = df.drop(columns= "Stock Splits")

In [25]:
df = df.sort_values(by= "Date", ascending=False)
df

,Date,Open,High,Low,Close,Volume
11524,2026-09-04 00:00:00-04:00,328.309998,328.929993,317.859985,319.970001,39551800
11523,2026-09-03 00:00:00-04:00,324.869995,330.809998,324.109985,328.209991,37225800
11522,2026-09-02 00:00:00-04:00,326.869995,328.399994,323.529999,324.959991,33776400
11521,2026-09-01 00:00:00-04:00,316.980011,327.299988,314.730011,325.130005,53167400
11520,2026-08-31 00:00:00-04:00,319.600006,321.239990,312.799988,316.850006,41242700
...,...,...,...,...,...,...
4,1980-12-18 00:00:00-05:00,0.090870,0.091297,0.090870,0.090870,73449600
3,1980-12-17 00:00:00-05:00,0.088310,0.088737,0.088310,0.088310,86441600
2,1980-12-16 00:00:00-05:00,0.086604,0.086604,0.086177,0.086177,105728000
1,1980-12-15 00:00:00-05:00,0.093430,0.093430,0.093003,0.093003,175884800
0,1980-12-12 00:00:00-05:00,0.098122,0.098549,0.098122,0.098122,469033600